name: auto_route_example
description: "An example of a Flutter project combining disco and auto_route."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  auto_route: ^11.0.0
  disco:
    path: ../../packages/disco
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
