name: _
publish_to: none
environment:
  sdk: ^3.10.0
workspace:
  - packages/disco
  - packages/disco/example
  - packages/disco_lint
  - packages/disco_lint/example
  - examples/auto_route
  - examples/bloc
  - examples/solidart
  - examples/preferences

flutter:
  uses-material-design: true
