name: disco_lint
description: disco_lint is a developer tool for users of disco, designed to help stop common issues and simplify repetitive tasks
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3
  
resolution: workspace

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.10
  analysis_server_plugin: ^0.3.3
  collection: ^1.19.1
  meta: ^1.17.0
  path: ^1.9.1
  source_span: ^1.10.1
  build: ^4.0.3
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.2
