name: disco
description: A Flutter library bringing a new concept of scoped providers for dependency injection, which are independent of any specific state management solution.
version: 2.0.0
repository: https://github.com/our-creativity/disco
homepage: https://disco.mariuti.com
documentation: https://disco.mariuti.com
topics:
  - dependency-injection
  - scope
  - provider

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  very_good_analysis: ^10.0.0
